test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Here we set the S3 bucket to the appropriate style, unless we override it in the ENV variables.
<% s3_bucket = Figaro.env.AWS_S3_BUCKET.nil? ? "caucus-#{(Hash["production", "prod", "development", "dev", "test", "ci"])[Rails.env]}" : Figaro.env.AWS_S3_BUCKET %>

amazon:
  service: S3
  access_key_id: <%= Figaro.env.AWS_ACCESS_KEY_ID %>
  secret_access_key: <%= Figaro.env.AWS_SECRET_ACCESS_KEY %>
  region: <%= Figaro.env.AWS_REGION %>
  bucket: <%= s3_bucket %>
# The above bucket is to shoehorn in the titles to the S3 buckets we've created
# So the buckets are "caucus-prod" "caucus-ci" "caucus-dev"

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
