# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

categories = [
  "Criminal Justice",
  "Elections",
  "Employment",
  "Governance",
  "Guns",
  "Personal Health",
  "Health Care",
  "Impeachment",
  "Retirement",
  "Taxes",
  "Trade",
  "Iowa",
  "Foreign Policy",
  "Vermont",
  "Sports",
  "Jobs",
  "Labor",
  "Texas",
  "Children",
  "Population",
  "Consumer Safety",
  "Voter ID Laws",
  "Automatic Voter Registration",
  "Crime",
  "Civil Rights",
  "Social Security",
  "Obama birth certificate",
  "China",
  "Animals",
  "City Government",
  "Transportation",
  "Illinois",
  "Oregon",
  "Iran",
  "City Budget",
  "Budget",
  "Federal Deficit",
  "County Budget",
  "Science",
  "Homelessness",
  "Disinfectants",
  "Impeachment Inquiry",
  "Gun Control",
  "Gun Violence",
  "Hispanic Unemployment",
  "Unemployment",
  "Black Unemployment",
  "Virginia",
  "International",
  "Ukraine",
  "Coronavirus",
  "2020 Election",
  "Social Security",
  "Infectious disease",
  "Vaccines",
  "Virus",
  "Washington State",
  "Washington D.C.",
  "Russia investigation",
  "Mueller Report",
  "Hong Kong",
  "Venezuela",
  "Wildfires",
  "Iraq",
  "Bankruptcy",
  "Affordable Care Act",
  "Preexisting Conditions",
  "Selective Service",
  "Illegal immigration",
  "Alabama",
  "Abortion",
  "Terrorism",
  "Iran Nuclear Deal",
  "Afghanistan",
  "Military",
  "Soldiers",
  "Troops",
  "Military Deaths",
  "9/11",
  "Michigan",
  "Domestic Violence",
  "Violence Against Women Act",
  "Religion",
  "Christianity",
  "Judaism",
  "Islam",
  "Hinduism",
  "Sikhism"
]

categories.each { |category| Category.create({ name: category }) }
