name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Run tests
      env:
        SECRET_KEY_BASE: XXXXXXX
        FACT_STREAM_BASE_URI: https://www.factstream.co
        MAILGUN_API_KEY: XXXXXXX
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails test

