name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Rubocop Linter Action
      uses: andrewmcodes/rubocop-linter-action@v3.0.0
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails test

